port = 5433
max_wal_size = 8GB
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9
wal_compression = on
eviction_algorithm = lru
autovacuum = off
maintenance_work_mem = 64MB
work_mem = 8MB
effective_cache_size = 2GB
log_min_messages = debug2
logging_collector = on
log_directory = 'pg_log'
log_filename = 'evict_test.log'
